title: MINJI,PARK
description: "나중"
site_title: 'MINJI PARK'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: qkralswl689
blog_url: https://qkralswl689.github.io
email:
keybase_username: qkralswl689
reddit_username: abhn

# absolute or relative
profile_picture: assets/images/pp.jpg

# Google Analytics ID
google_analytics:
